/**
 * action type
 */
export enum SocketAction {
  CLIENT_PING = 'CLIENT_PING_ACTION',
  CLIENT_QUERY = 'CLIENT_QUERY_ACTION',
  QUERY_RESULT = 'QUERY_RESULT_ACTION',
  QUERY_HISTORY_MESSAGE = 'QUERY_HISTORY_MESSAGE_ACTION',
  MESSAGE_READ = 'MESSAGE_READ_ACTION',
  REGISTER_GROUP = 'REGISTER_GROUP_ACTION',
  SEND_MESSAGE_USER = 'SEND_MESSAGE_USER_ACTION',
  SERVER_PUSH_MESSAGE = 'SERVER_PUSH_MESSAGE_ACTION',
  SUM_MESSAGE_ACTION = 'SUM_MESSAGE_ACTION'
}
